export const categories = [
    'Captions available',
    'Co-op',
    'Commentary available',
    'Cross-Platform Multiplayer',
    'Full controller support',
    'HDR available',
    'In-App Purchases',
    'Includes Source SDK',
    'Includes level editor',
    'LAN Co-op',
    'LAN PvP',
    'MMO',
    'Mods',
    'Mods (require HL2)',
    'Multi-player',
    'Online Co-op',
    'Online PvP',
    'Partial Controller Support',
    'PvP',
    'Remote Play Together',
    'Remote Play on Phone',
    'Remote Play on TV',
    'Remote Play on Tablet',
    'Shared/Split Screen',
    'Shared/Split Screen Co-op',
    'Shared/Split Screen PvP',
    'Single-player',
    'Stats',
    'Steam Achievements',
    'Steam Cloud',
    'Steam Leaderboards',
    'Steam Trading Cards',
    'Steam Turn Notifications',
    'Steam Workshop',
    'SteamVR Collectibles',
    'Tracked Controller Support',
    'Tracked Motion Controller Support',
    'VR Only',
    'VR Support',
    'VR Supported',
    'Valve Anti-Cheat enabled'
];


export const genres = [
    '360 Video',
    'Accounting',
    'Action',
    'Adventure',
    'Animation & Modeling',
    'Audio Production',
    'Casual',
    'Design & Illustration',
    'Documentary',
    'Early Access',
    'Education',
    'Episodic',
    'Free to Play',
    'Game Development',
    'Gore',
    'Indie',
    'Massively Multiplayer',
    'Movie',
    'Nudity',
    'Photo Editing',
    'RPG',
    'Racing',
    'Sexual Content',
    'Short',
    'Simulation',
    'Software Training',
    'Sports',
    'Strategy',
    'Tutorial',
    'Utilities',
    'Video Production',
    'Violent',
    'Web Publishing'
];

export const sortBys = [
    'ReleaseDate',
    'Price',
    'Name',
    'MetaScore',
    'Positive',
    'Negative'
];